site_name: Technical Writing Assistant
site_description: AI-powered technical documentation review system
site_url: https://yourusername.github.io/tech-writer-assistant

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - Installation: user-guide/installation.md
      - First Review: user-guide/first-review.md
      - Understanding Results: user-guide/understanding-results.md
  - API Reference:
      - Overview: api/overview.md
  - Architecture:
      - System Overview: architecture/overview.md
      - Document Processing: architecture/document-processing.md
      - Security: architecture/security.md
  - Development:
      - Contributing: development/contributing.md
      - Testing: development/testing.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_bases: true
            show_root_heading: true
            show_root_members_full_path: false
            merge_init_into_class: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/tech-writer-assistant
